dependencies {
	compileInclude group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileInclude group: "com.mysql", name: "mysql-connector-j", version: "8.0.33"
	compileInclude group: "junit", name: "junit", version: "4.13.1"
	compileInclude project(":core:petra:petra-function")
	compileInclude project(":core:petra:petra-lang")
	compileInclude project(":core:petra:petra-string")
	compileInclude project(":util:portal-test-http-util")
}

test {
	systemProperties(
		System.properties.subMap([
			"benchmarks.test.excluded.company.web.ids",
			"benchmarks.test.jdbc.driverClassName",
			"benchmarks.test.jdbc.password",
			"benchmarks.test.jdbc.url",
			"benchmarks.test.jdbc.username",
			"benchmarks.test.run.count",
			"benchmarks.test.skip.warm.up",
			"benchmarks.test.thread.count",
			"benchmarks.test.user.password"
		])
	)
}