/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LayoutCT;
import com.liferay.portal.kernel.model.LayoutCTModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.persistence.LayoutCTPK;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the LayoutCT service. Represents a row in the &quot;LayoutCT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LayoutCTModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutCTImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutCTImpl
 * @generated
 */
@ProviderType
public class LayoutCTModelImpl
	extends BaseModelImpl<LayoutCT> implements LayoutCTModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout ct model instance should use the <code>LayoutCT</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutCT";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"plid", Types.BIGINT},
		{"ctCollectionId", Types.BIGINT}, {"typeSettings", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeSettings", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutCT (mvccVersion LONG default 0 not null,plid LONG not null,ctCollectionId LONG not null,typeSettings VARCHAR(75) null,primary key (plid, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table LayoutCT";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutCT.id.plid ASC, layoutCT.id.ctCollectionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutCT.plid ASC, LayoutCT.ctCollectionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.util.PropsUtil.get(
			"value.object.entity.cache.enabled.com.liferay.portal.kernel.model.LayoutCT"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.util.PropsUtil.get(
			"value.object.finder.cache.enabled.com.liferay.portal.kernel.model.LayoutCT"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.util.PropsUtil.get(
			"value.object.column.bitmask.enabled.com.liferay.portal.kernel.model.LayoutCT"),
		true);

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 1L;

	public static final long PLID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.LayoutCT"));

	public LayoutCTModelImpl() {
	}

	@Override
	public LayoutCTPK getPrimaryKey() {
		return new LayoutCTPK(_plid, _ctCollectionId);
	}

	@Override
	public void setPrimaryKey(LayoutCTPK primaryKey) {
		setPlid(primaryKey.plid);
		setCtCollectionId(primaryKey.ctCollectionId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new LayoutCTPK(_plid, _ctCollectionId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((LayoutCTPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutCT.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutCT.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutCT, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutCT, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutCT, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LayoutCT)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutCT, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutCT, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutCT)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutCT, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutCT, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LayoutCT>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LayoutCT.class.getClassLoader(), LayoutCT.class,
			ModelWrapper.class);

		try {
			Constructor<LayoutCT> constructor =
				(Constructor<LayoutCT>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<LayoutCT, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LayoutCT, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LayoutCT, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LayoutCT, Object>>();
		Map<String, BiConsumer<LayoutCT, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LayoutCT, ?>>();

		attributeGetterFunctions.put("mvccVersion", LayoutCT::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<LayoutCT, Long>)LayoutCT::setMvccVersion);
		attributeGetterFunctions.put("plid", LayoutCT::getPlid);
		attributeSetterBiConsumers.put(
			"plid", (BiConsumer<LayoutCT, Long>)LayoutCT::setPlid);
		attributeGetterFunctions.put(
			"ctCollectionId", LayoutCT::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<LayoutCT, Long>)LayoutCT::setCtCollectionId);
		attributeGetterFunctions.put("typeSettings", LayoutCT::getTypeSettings);
		attributeSetterBiConsumers.put(
			"typeSettings",
			(BiConsumer<LayoutCT, String>)LayoutCT::setTypeSettings);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_columnBitmask |= PLID_COLUMN_BITMASK;

		if (!_setOriginalPlid) {
			_setOriginalPlid = true;

			_originalPlid = _plid;
		}

		_plid = plid;
	}

	public long getOriginalPlid() {
		return _originalPlid;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (!_setOriginalCtCollectionId) {
			_setOriginalCtCollectionId = true;

			_originalCtCollectionId = _ctCollectionId;
		}

		_ctCollectionId = ctCollectionId;
	}

	public long getOriginalCtCollectionId() {
		return _originalCtCollectionId;
	}

	@Override
	public String getTypeSettings() {
		if (_typeSettings == null) {
			return "";
		}
		else {
			return _typeSettings;
		}
	}

	@Override
	public void setTypeSettings(String typeSettings) {
		_typeSettings = typeSettings;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public LayoutCT toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LayoutCT>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutCTImpl layoutCTImpl = new LayoutCTImpl();

		layoutCTImpl.setMvccVersion(getMvccVersion());
		layoutCTImpl.setPlid(getPlid());
		layoutCTImpl.setCtCollectionId(getCtCollectionId());
		layoutCTImpl.setTypeSettings(getTypeSettings());

		layoutCTImpl.resetOriginalValues();

		return layoutCTImpl;
	}

	@Override
	public int compareTo(LayoutCT layoutCT) {
		LayoutCTPK primaryKey = layoutCT.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutCT)) {
			return false;
		}

		LayoutCT layoutCT = (LayoutCT)obj;

		LayoutCTPK primaryKey = layoutCT.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LayoutCTModelImpl layoutCTModelImpl = this;

		layoutCTModelImpl._originalPlid = layoutCTModelImpl._plid;

		layoutCTModelImpl._setOriginalPlid = false;

		layoutCTModelImpl._originalCtCollectionId =
			layoutCTModelImpl._ctCollectionId;

		layoutCTModelImpl._setOriginalCtCollectionId = false;

		layoutCTModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutCT> toCacheModel() {
		LayoutCTCacheModel layoutCTCacheModel = new LayoutCTCacheModel();

		layoutCTCacheModel.layoutCTPK = getPrimaryKey();

		layoutCTCacheModel.mvccVersion = getMvccVersion();

		layoutCTCacheModel.plid = getPlid();

		layoutCTCacheModel.ctCollectionId = getCtCollectionId();

		layoutCTCacheModel.typeSettings = getTypeSettings();

		String typeSettings = layoutCTCacheModel.typeSettings;

		if ((typeSettings != null) && (typeSettings.length() == 0)) {
			layoutCTCacheModel.typeSettings = null;
		}

		return layoutCTCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutCT, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutCT, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutCT, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LayoutCT)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LayoutCT, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LayoutCT, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutCT, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LayoutCT)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LayoutCT>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _plid;
	private long _originalPlid;
	private boolean _setOriginalPlid;
	private long _ctCollectionId;
	private long _originalCtCollectionId;
	private boolean _setOriginalCtCollectionId;
	private String _typeSettings;
	private long _columnBitmask;
	private LayoutCT _escapedModel;

}