/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.kernel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.service.persistence.LayoutCTPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LayoutCT service. Represents a row in the &quot;LayoutCT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.model.impl.LayoutCTModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.model.impl.LayoutCTImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutCT
 * @generated
 */
@ProviderType
public interface LayoutCTModel extends BaseModel<LayoutCT>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout ct model instance should use the {@link LayoutCT} interface instead.
	 */

	/**
	 * Returns the primary key of this layout ct.
	 *
	 * @return the primary key of this layout ct
	 */
	public LayoutCTPK getPrimaryKey();

	/**
	 * Sets the primary key of this layout ct.
	 *
	 * @param primaryKey the primary key of this layout ct
	 */
	public void setPrimaryKey(LayoutCTPK primaryKey);

	/**
	 * Returns the mvcc version of this layout ct.
	 *
	 * @return the mvcc version of this layout ct
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this layout ct.
	 *
	 * @param mvccVersion the mvcc version of this layout ct
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the plid of this layout ct.
	 *
	 * @return the plid of this layout ct
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout ct.
	 *
	 * @param plid the plid of this layout ct
	 */
	public void setPlid(long plid);

	/**
	 * Returns the ct collection ID of this layout ct.
	 *
	 * @return the ct collection ID of this layout ct
	 */
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this layout ct.
	 *
	 * @param ctCollectionId the ct collection ID of this layout ct
	 */
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the type settings of this layout ct.
	 *
	 * @return the type settings of this layout ct
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this layout ct.
	 *
	 * @param typeSettings the type settings of this layout ct
	 */
	public void setTypeSettings(String typeSettings);

}