/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.sample.sql.builder;

import com.liferay.blogs.model.BlogsEntryModel;
import com.liferay.blogs.model.BlogsStatsUserModel;
import com.liferay.blogs.model.impl.BlogsEntryModelImpl;
import com.liferay.blogs.model.impl.BlogsStatsUserModelImpl;
import com.liferay.friendly.url.model.FriendlyURLEntryLocalizationModel;
import com.liferay.friendly.url.model.FriendlyURLEntryMappingModel;
import com.liferay.friendly.url.model.FriendlyURLEntryModel;
import com.liferay.friendly.url.model.impl.FriendlyURLEntryLocalizationModelImpl;
import com.liferay.friendly.url.model.impl.FriendlyURLEntryMappingModelImpl;
import com.liferay.friendly.url.model.impl.FriendlyURLEntryModelImpl;
import com.liferay.portal.kernel.util.LocaleUtil;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * @author Lily Chi
 */
public class BlogDataFactory extends BaseDataFactory {

	public static BlogDataFactory getInstance() {
		return _blogFactory;
	}

	public int getMaxBlogsEntryCommentCount() {
		return BenchmarksPropsValues.MAX_BLOGS_ENTRY_COMMENT_COUNT;
	}

	public List<BlogsEntryModel> newBlogsEntryModels(long groupId) {
		List<BlogsEntryModel> blogEntryModels = new ArrayList<>(
			BenchmarksPropsValues.MAX_BLOGS_ENTRY_COUNT);

		for (int i = 1; i <= BenchmarksPropsValues.MAX_BLOGS_ENTRY_COUNT; i++) {
			blogEntryModels.add(_newBlogsEntryModel(groupId, i));
		}

		return blogEntryModels;
	}

	public BlogsStatsUserModel newBlogsStatsUserModel(long groupId) {
		BlogsStatsUserModel blogsStatsUserModel = new BlogsStatsUserModelImpl();

		// PK fields

		blogsStatsUserModel.setStatsUserId(counter.get());

		// Group instance

		blogsStatsUserModel.setGroupId(groupId);

		// Audit fields

		blogsStatsUserModel.setCompanyId(COMPANY_ID);
		blogsStatsUserModel.setUserId(SAMPLE_USER_ID);

		// Other fields

		blogsStatsUserModel.setEntryCount(
			BenchmarksPropsValues.MAX_BLOGS_ENTRY_COUNT);
		blogsStatsUserModel.setLastPostDate(new Date());

		return blogsStatsUserModel;
	}

	public FriendlyURLEntryLocalizationModel
		newFriendlyURLEntryLocalizationModel(
			FriendlyURLEntryModel friendlyURLEntryModel,
			BlogsEntryModel blogsEntryModel) {

		FriendlyURLEntryLocalizationModel friendlyURLEntryLocalizationModel =
			new FriendlyURLEntryLocalizationModelImpl();

		// PK fields

		friendlyURLEntryLocalizationModel.setFriendlyURLEntryLocalizationId(
			counter.get());

		// Group instance

		friendlyURLEntryLocalizationModel.setGroupId(
			friendlyURLEntryModel.getGroupId());

		// Audit fields

		friendlyURLEntryLocalizationModel.setCompanyId(
			friendlyURLEntryModel.getCompanyId());

		// Other fields

		friendlyURLEntryLocalizationModel.setClassNameId(
			friendlyURLEntryModel.getClassNameId());
		friendlyURLEntryLocalizationModel.setClassPK(
			friendlyURLEntryModel.getClassPK());
		friendlyURLEntryLocalizationModel.setUrlTitle(
			blogsEntryModel.getUrlTitle());

		// Autogenerated fields

		friendlyURLEntryLocalizationModel.setFriendlyURLEntryId(
			friendlyURLEntryModel.getFriendlyURLEntryId());
		friendlyURLEntryLocalizationModel.setLanguageId(
			LocaleUtil.toLanguageId(LocaleUtil.getSiteDefault()));

		return friendlyURLEntryLocalizationModel;
	}

	public FriendlyURLEntryMappingModel newFriendlyURLEntryMapping(
		FriendlyURLEntryModel friendlyURLEntryModel) {

		FriendlyURLEntryMappingModel friendlyURLEntryMappingModel =
			new FriendlyURLEntryMappingModelImpl();

		// PK fields

		friendlyURLEntryMappingModel.setFriendlyURLEntryMappingId(
			counter.get());

		//  Other fields

		friendlyURLEntryMappingModel.setClassNameId(
			friendlyURLEntryModel.getClassNameId());
		friendlyURLEntryMappingModel.setClassPK(
			friendlyURLEntryModel.getClassPK());
		friendlyURLEntryMappingModel.setFriendlyURLEntryId(
			friendlyURLEntryModel.getFriendlyURLEntryId());

		return friendlyURLEntryMappingModel;
	}

	public FriendlyURLEntryModel newFriendlyURLEntryModel(
		BlogsEntryModel blogsEntryModel, long classNameId) {

		FriendlyURLEntryModel friendlyURLEntryModel =
			new FriendlyURLEntryModelImpl();

		// UUID

		friendlyURLEntryModel.setUuid(SequentialUUID.generate());

		// PK fields

		friendlyURLEntryModel.setFriendlyURLEntryId(counter.get());

		// Group instance

		friendlyURLEntryModel.setGroupId(blogsEntryModel.getGroupId());

		// Audit fields

		friendlyURLEntryModel.setCompanyId(COMPANY_ID);
		friendlyURLEntryModel.setCreateDate(new Date());
		friendlyURLEntryModel.setModifiedDate(new Date());

		// Other fields

		friendlyURLEntryModel.setClassNameId(classNameId);
		friendlyURLEntryModel.setClassPK(blogsEntryModel.getEntryId());

		// Autogenerated fields

		friendlyURLEntryModel.setDefaultLanguageId("en_US");

		return friendlyURLEntryModel;
	}

	private BlogDataFactory() {
	}

	private BlogsEntryModel _newBlogsEntryModel(long groupId, int index) {
		BlogsEntryModel blogsEntryModel = new BlogsEntryModelImpl();

		// UUID

		blogsEntryModel.setUuid(SequentialUUID.generate());

		// PK fields

		blogsEntryModel.setEntryId(counter.get());

		// Group instance

		blogsEntryModel.setGroupId(groupId);

		// Audit fields

		blogsEntryModel.setCompanyId(COMPANY_ID);
		blogsEntryModel.setUserId(SAMPLE_USER_ID);
		blogsEntryModel.setUserName(SAMPLE_USER_NAME);
		blogsEntryModel.setCreateDate(new Date());
		blogsEntryModel.setModifiedDate(new Date());

		// Other field

		blogsEntryModel.setTitle("Test Blog " + index);
		blogsEntryModel.setSubtitle("Subtitle of Test Blog " + index);
		blogsEntryModel.setUrlTitle("testblog" + index);
		blogsEntryModel.setContent("This is test blog " + index + ".");
		blogsEntryModel.setDisplayDate(new Date());
		blogsEntryModel.setLastPublishDate(new Date());
		blogsEntryModel.setStatusByUserId(SAMPLE_USER_ID);
		blogsEntryModel.setStatusDate(new Date());

		return blogsEntryModel;
	}

	private static BlogDataFactory _blogFactory = new BlogDataFactory();

}