/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.production.readiness.ignore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IgnoredRule service. Represents a row in the &quot;IgnoredRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.production.readiness.ignore.model.impl.IgnoredRuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.production.readiness.ignore.model.impl.IgnoredRuleImpl</code>.
 * </p>
 *
 * @author Lily Chi
 * @see IgnoredRule
 * @generated
 */
@ProviderType
public interface IgnoredRuleModel
	extends AuditedModel, BaseModel<IgnoredRule>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ignored rule model instance should use the {@link IgnoredRule} interface instead.
	 */

	/**
	 * Returns the primary key of this ignored rule.
	 *
	 * @return the primary key of this ignored rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ignored rule.
	 *
	 * @param primaryKey the primary key of this ignored rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ignored rule.
	 *
	 * @return the mvcc version of this ignored rule
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ignored rule.
	 *
	 * @param mvccVersion the mvcc version of this ignored rule
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ignored rule ID of this ignored rule.
	 *
	 * @return the ignored rule ID of this ignored rule
	 */
	public long getIgnoredRuleId();

	/**
	 * Sets the ignored rule ID of this ignored rule.
	 *
	 * @param ignoredRuleId the ignored rule ID of this ignored rule
	 */
	public void setIgnoredRuleId(long ignoredRuleId);

	/**
	 * Returns the company ID of this ignored rule.
	 *
	 * @return the company ID of this ignored rule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ignored rule.
	 *
	 * @param companyId the company ID of this ignored rule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ignored rule.
	 *
	 * @return the user ID of this ignored rule
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ignored rule.
	 *
	 * @param userId the user ID of this ignored rule
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ignored rule.
	 *
	 * @return the user uuid of this ignored rule
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ignored rule.
	 *
	 * @param userUuid the user uuid of this ignored rule
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ignored rule.
	 *
	 * @return the user name of this ignored rule
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ignored rule.
	 *
	 * @param userName the user name of this ignored rule
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ignored rule.
	 *
	 * @return the create date of this ignored rule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ignored rule.
	 *
	 * @param createDate the create date of this ignored rule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ignored rule.
	 *
	 * @return the modified date of this ignored rule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ignored rule.
	 *
	 * @param modifiedDate the modified date of this ignored rule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the rule key of this ignored rule.
	 *
	 * @return the rule key of this ignored rule
	 */
	@AutoEscape
	public String getRuleKey();

	/**
	 * Sets the rule key of this ignored rule.
	 *
	 * @param ruleKey the rule key of this ignored rule
	 */
	public void setRuleKey(String ruleKey);

	/**
	 * Returns the reason of this ignored rule.
	 *
	 * @return the reason of this ignored rule
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this ignored rule.
	 *
	 * @param reason the reason of this ignored rule
	 */
	public void setReason(String reason);

	@Override
	public IgnoredRule cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-223060251