##
## Test Suites
##

    modified.files.includes[relevant][glowroot-integration-java-rule]=\
        **/*.java,\
        **/testIntegration/**

    relevant.rule.names=\
        glowroot-integration-java-rule

    test.batch.names[relevant][glowroot-integration-java-rule]=\
        glowroot-integration

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant][glowroot-integration-java-rule]=\
        glowroot/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][glowroot-integration-java-rule]=\
        glowroot/**/*Test.java

    test.batch.run.property.query[relevant][glowroot-integration-java-rule]=\
        (portal.acceptance == true) AND \
        (testray.component.names ~ "glowroot")

##
## Testray
##

    testray.main.component.name=glowroot
