<?xml version="1.0"?>

<project basedir="." default="run" name="benchmarks">
	<import file="../build-common.xml" />

	<property name="build.dir" value="build" />

	<target depends="clean" name="build-sample-sql">
		<property name="sample.sql.output.dir" value="${basedir}/${build.dir}" />

		<property name="output.sql.file" value="sample-data-${sample.sql.db.type}.sql" />

		<gradle-execute dir="../modules/util/portal-tools-sample-sql-builder" task="jar" />

		<echoproperties destfile="benchmarks-actual.properties" prefix="sample.sql." />

		<java
			classname="com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderLauncher"
			dir="."
			fork="true"
		>
			<classpath>
				<fileset
					dir="${sdk.dir}/dist"
					includes="com.liferay.portal.tools.sample.sql.builder*.jar"
				/>
				<path refid="project.classpath" />
			</classpath>
			<sysproperty key="external-properties" value="com/liferay/portal/tools/dependencies/portal-tools.properties" />
			<sysproperty key="sample-sql-properties" value="${basedir}/benchmarks-actual.properties" />
		</java>

		<concat append="true" destfile="${output.sql.file}">
			<filelist dir="../sql/portal/" files="portal-${sample.sql.db.type}.sql" />
			<filelist dir="../sql/indexes/" files="indexes-${sample.sql.db.type}.sql" />
		</concat>

		<for list="${portal.module.dir.list}" param="module">
			<sequential>
				<ant antfile="../sql/build.xml" inheritall="false" target="build-db">
					<property name="db.sql.dir" value="@{module}" />
				</ant>

				<concat append="true" destfile="${output.sql.file}">
					<filelist dir="@{module}/tables/" files="tables-${sample.sql.db.type}.sql" />
					<filelist dir="@{module}/indexes/" files="indexes-${sample.sql.db.type}.sql" />
				</concat>
			</sequential>
		</for>

		<property name="sample.sql.create.single.file" value="true" />

		<if>
			<istrue value="${sample.sql.create.single.file}" />
			<then>
				<if>
					<istrue value="${sample.sql.output.merge}" />
					<then>
						<concat append="true" destfile="${output.sql.file}">
							<filelist dir="${sample.sql.output.dir}" files="sample-${sample.sql.db.type}.sql" />
						</concat>
					</then>
					<else>
						<for param="sql-file-filename">
							<path>
								<fileset
									dir="${sample.sql.output.dir}/output"
									includes="*.sql"
								/>
							</path>
							<sequential>
								<concat append="true" destfile="${output.sql.file}">
									<filelist dir="${sample.sql.output.dir}/output" files="@{sql-file-filename}" />
								</concat>
							</sequential>
						</for>
					</else>
				</if>
			</then>
		</if>
		<echo>
Sample SQL Build Successful
Use ${basedir}/${output.sql.file} to insert into database.</echo>
	</target>

	<target name="clean">
		<delete includeemptydirs="true">
			<fileset
				dir="."
				includes="benchmarks-actual.properties, liferay/**, ${build.dir}/**"
			/>
		</delete>
	</target>
</project>