<?xml version="1.0"?>

<project basedir="." default="run" name="benchmarks">
	<import file="../build-common.xml" />

	<target name="build-sample-sql">
		<gradle-execute dir="../modules/util/portal-tools-sample-sql-builder" task="jar" />

		<beanshell>
			InputStream inputStream = new FileInputStream("benchmarks.properties");
			OutputStream outputStream = new FileOutputStream("benchmarks-merged.properties");

			Properties properties = new Properties();

			properties.load(inputStream);

			for (String propertyKey : properties.stringPropertyNames()) {
				properties.setProperty(propertyKey, project.getProperty(propertyKey));
			}

			properties.store(outputStream, "");

			inputStream.close();
			outputStream.close();
		</beanshell>

		<property name="sample.sql.properties.file" value="benchmarks-merged.properties" />

		<java
			classname="com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderLauncher"
			dir="."
			fork="true"
		>
			<classpath>
				<fileset
					dir="${sdk.dir}/dist"
					includes="com.liferay.portal.tools.sample.sql.builder*.jar"
				/>
				<path refid="project.classpath" />
			</classpath>
			<sysproperty key="external-properties" value="com/liferay/portal/tools/dependencies/portal-tools.properties" />
			<sysproperty key="sample-sql-properties" value="${sample.sql.properties.file}" />
		</java>
	</target>

	<target name="clean">
		<delete includeemptydirs="true">
			<fileset
				dir="."
				includes="*.csv,*.sql,benchmarks-actual.properties,output/**,temp/**"
			/>
		</delete>
	</target>
</project>