/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.production.readiness.ignore.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.production.readiness.ignore.model.IgnoredRule;
import com.liferay.production.readiness.ignore.model.IgnoredRuleModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the IgnoredRule service. Represents a row in the &quot;IgnoredRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>IgnoredRuleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IgnoredRuleImpl}.
 * </p>
 *
 * @author Lily Chi
 * @see IgnoredRuleImpl
 * @generated
 */
public class IgnoredRuleModelImpl
	extends BaseModelImpl<IgnoredRule> implements IgnoredRuleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ignored rule model instance should use the <code>IgnoredRule</code> interface instead.
	 */
	public static final String TABLE_NAME = "IgnoredRule";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ignoredRuleId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ruleKey", Types.VARCHAR},
		{"reason", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ignoredRuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ruleKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IgnoredRule (mvccVersion LONG default 0 not null,ignoredRuleId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ruleKey VARCHAR(75) null,reason VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table IgnoredRule";

	public static final String ENTITY_ALIAS = "ignoredRule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ignoredRule.ignoredRuleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IgnoredRule.ignoredRuleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RULEKEY_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IGNOREDRULEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public IgnoredRuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ignoredRuleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIgnoredRuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ignoredRuleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IgnoredRule.class;
	}

	@Override
	public String getModelClassName() {
		return IgnoredRule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<IgnoredRule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<IgnoredRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IgnoredRule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((IgnoredRule)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<IgnoredRule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<IgnoredRule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(IgnoredRule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<IgnoredRule, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<IgnoredRule, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<IgnoredRule, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<IgnoredRule, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<IgnoredRule, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", IgnoredRule::getMvccVersion);
			attributeGetterFunctions.put(
				"ignoredRuleId", IgnoredRule::getIgnoredRuleId);
			attributeGetterFunctions.put(
				"companyId", IgnoredRule::getCompanyId);
			attributeGetterFunctions.put("userId", IgnoredRule::getUserId);
			attributeGetterFunctions.put("userName", IgnoredRule::getUserName);
			attributeGetterFunctions.put(
				"createDate", IgnoredRule::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", IgnoredRule::getModifiedDate);
			attributeGetterFunctions.put("ruleKey", IgnoredRule::getRuleKey);
			attributeGetterFunctions.put("reason", IgnoredRule::getReason);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<IgnoredRule, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<IgnoredRule, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<IgnoredRule, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<IgnoredRule, Long>)IgnoredRule::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ignoredRuleId",
				(BiConsumer<IgnoredRule, Long>)IgnoredRule::setIgnoredRuleId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<IgnoredRule, Long>)IgnoredRule::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<IgnoredRule, Long>)IgnoredRule::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<IgnoredRule, String>)IgnoredRule::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<IgnoredRule, Date>)IgnoredRule::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<IgnoredRule, Date>)IgnoredRule::setModifiedDate);
			attributeSetterBiConsumers.put(
				"ruleKey",
				(BiConsumer<IgnoredRule, String>)IgnoredRule::setRuleKey);
			attributeSetterBiConsumers.put(
				"reason",
				(BiConsumer<IgnoredRule, String>)IgnoredRule::setReason);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getIgnoredRuleId() {
		return _ignoredRuleId;
	}

	@Override
	public void setIgnoredRuleId(long ignoredRuleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ignoredRuleId = ignoredRuleId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getRuleKey() {
		if (_ruleKey == null) {
			return "";
		}
		else {
			return _ruleKey;
		}
	}

	@Override
	public void setRuleKey(String ruleKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ruleKey = ruleKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRuleKey() {
		return getColumnOriginalValue("ruleKey");
	}

	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), IgnoredRule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IgnoredRule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, IgnoredRule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IgnoredRuleImpl ignoredRuleImpl = new IgnoredRuleImpl();

		ignoredRuleImpl.setMvccVersion(getMvccVersion());
		ignoredRuleImpl.setIgnoredRuleId(getIgnoredRuleId());
		ignoredRuleImpl.setCompanyId(getCompanyId());
		ignoredRuleImpl.setUserId(getUserId());
		ignoredRuleImpl.setUserName(getUserName());
		ignoredRuleImpl.setCreateDate(getCreateDate());
		ignoredRuleImpl.setModifiedDate(getModifiedDate());
		ignoredRuleImpl.setRuleKey(getRuleKey());
		ignoredRuleImpl.setReason(getReason());

		ignoredRuleImpl.resetOriginalValues();

		return ignoredRuleImpl;
	}

	@Override
	public IgnoredRule cloneWithOriginalValues() {
		IgnoredRuleImpl ignoredRuleImpl = new IgnoredRuleImpl();

		ignoredRuleImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		ignoredRuleImpl.setIgnoredRuleId(
			this.<Long>getColumnOriginalValue("ignoredRuleId"));
		ignoredRuleImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ignoredRuleImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		ignoredRuleImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		ignoredRuleImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		ignoredRuleImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		ignoredRuleImpl.setRuleKey(
			this.<String>getColumnOriginalValue("ruleKey"));
		ignoredRuleImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));

		return ignoredRuleImpl;
	}

	@Override
	public int compareTo(IgnoredRule ignoredRule) {
		long primaryKey = ignoredRule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof IgnoredRule)) {
			return false;
		}

		IgnoredRule ignoredRule = (IgnoredRule)object;

		long primaryKey = ignoredRule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<IgnoredRule> toCacheModel() {
		IgnoredRuleCacheModel ignoredRuleCacheModel =
			new IgnoredRuleCacheModel();

		ignoredRuleCacheModel.mvccVersion = getMvccVersion();

		ignoredRuleCacheModel.ignoredRuleId = getIgnoredRuleId();

		ignoredRuleCacheModel.companyId = getCompanyId();

		ignoredRuleCacheModel.userId = getUserId();

		ignoredRuleCacheModel.userName = getUserName();

		String userName = ignoredRuleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ignoredRuleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ignoredRuleCacheModel.createDate = createDate.getTime();
		}
		else {
			ignoredRuleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ignoredRuleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ignoredRuleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ignoredRuleCacheModel.ruleKey = getRuleKey();

		String ruleKey = ignoredRuleCacheModel.ruleKey;

		if ((ruleKey != null) && (ruleKey.length() == 0)) {
			ignoredRuleCacheModel.ruleKey = null;
		}

		ignoredRuleCacheModel.reason = getReason();

		String reason = ignoredRuleCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			ignoredRuleCacheModel.reason = null;
		}

		return ignoredRuleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<IgnoredRule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<IgnoredRule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IgnoredRule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((IgnoredRule)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, IgnoredRule>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					IgnoredRule.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ignoredRuleId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ruleKey;
	private String _reason;

	public <T> T getColumnValue(String columnName) {
		Function<IgnoredRule, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((IgnoredRule)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ignoredRuleId", _ignoredRuleId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("ruleKey", _ruleKey);
		_columnOriginalValues.put("reason", _reason);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ignoredRuleId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("ruleKey", 128L);

		columnBitmasks.put("reason", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private IgnoredRule _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1252492589