/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.production.readiness.ignore.model.impl;

import com.liferay.production.readiness.ignore.model.IgnoredRule;
import com.liferay.production.readiness.ignore.service.IgnoredRuleLocalServiceUtil;

/**
 * The extended model base implementation for the IgnoredRule service. Represents a row in the &quot;IgnoredRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IgnoredRuleImpl}.
 * </p>
 *
 * @author Lily Chi
 * @see IgnoredRuleImpl
 * @see IgnoredRule
 * @generated
 */
public abstract class IgnoredRuleBaseImpl
	extends IgnoredRuleModelImpl implements IgnoredRule {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ignored rule model instance should use the <code>IgnoredRule</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			IgnoredRuleLocalServiceUtil.addIgnoredRule(this);
		}
		else {
			IgnoredRuleLocalServiceUtil.updateIgnoredRule(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1902211709